export interface eccotiz {
  aud_esta    :string;
aud_usua    :string;
aud_ufac    :string;
emp_codi    :string;
cot_cont    :string;
top_codi    :string;
cot_nume    :string;
cot_fech    :string;
cot_nech    :string;
cot_anop    :string;
cot_mesp    :string;
cot_diap    :string;
cot_esta    :string;
cas_cont    :string;
cot_fvec    :string;
cot_fing    :string;
cot_ndia    :string;
cot_fsal    :string;
cot_nver    :string;
soc_cont    :string;
mac_nume    :string;
sbe_cont    :string;
cot_orga    :string;
cot_norg    :string;
cot_torg    :string;
cot_coor    :string;
cot_ncoo    :string;
cot_tcoo    :string;
ter_ejec    :string;
ter_capi    :string;
cot_mail    :string;
cot_desc    :string;
cot_obse    :string;
cot_prot    :string;
ite_cont    :string;
cot_fpag    :string;
cli_codi    :string;
dcl_codd    :string;
con_codi    :string;
arb_sucu    :string;
coc_codi    :string;
act_cont    :string;
mon_codi    :string;
cot_feta    :string;
cot_vata    :string;
lip_cont    :string;
for_codi    :string;
cot_vato    :string;
cot_gccl    :string;
cot_ncon    :string;
cot_plaz    :string;
cot_upla    :string;
cot_objc    :string;
cot_dcre    :string;
ite_mcan    :string;
con_cont    :string;
eve_cont    :string;
cot_ecor    :string;
top_nomb    :string;
soc_codi    :string;
sbe_codi    :string;
sbe_noco    :string;
sbe_ncar    :string;
ter_coda_ej :string;
ter_noco_ej :string;
ter_coda_ca :string;
ter_noco_ca :string;
ite_codi    :string;
ite_nomb    :string;
cli_coda    :string;
cli_noco    :string;
dcl_nomb    :string;
con_nomb    :string;
arb_codi    :string;
arb_nomb    :string;
coc_nomb    :string;
act_codi    :string;
act_nomb    :string;
mon_nomb    :string;
lip_codi    :string;
lip_desc    :string;
for_nomb    :string;
ite_codi_mc :string;
ite_nomb_mc	:string;
detalle: TOEcDespa[];
anticipos:TOEcDetan[];
liquidacion:TOLiqCons[];
}

export  interface TOEcDespa {
  emp_codi:string;
  cot_cont:string;
  des_cont:string;
  des_fing:string;
  des_ndia:string;
  des_fsal:string;
  esp_cont:string;
  des_capa:string;
  ter_codi:string;
  des_dinv:string;
  des_ninv:string;
  pro_cont:string;
  des_tari:string;
  des_tdes:string;
  des_vdes:string;
  des_care:string;
  res_cont:string;
  esp_codi:string;
  esp_nomb:string;
  cla_cont:string;
  cla_codi:string;
  cla_nomb:string;
  cla_clti:string;
  lip_cont:string;
  tip_cont:string;
  tip_codi:string;
  tip_nomb:string;
  ter_coda:string;
  ter_noco:string;
  tip_abre:string;
  pro_codi:string;
  pro_nomb:string;
  bod_codi:string;
  res_fech:string;
  res_fini:string;
  esp_mdit:string;
  productos:TOEcDphij[];
  clase:TOAeClase;
}
export interface TOEcDetan {
  emp_codi:string;
cot_cont:string;
det_cont:string;
fac_cont:string;
det_vant:string;
det_vleg:string;
det_sald:string;
top_codi:string;
fac_nume:string;
fac_fech:string;
cli_codi:string;
top_nomb:string;
}
export interface TOLiqCons {
  emp_codi:string;
cot_cont:string;
liq_cons:string;
liq_codi:string;
liq_nomb:string;
liq_valo:string;
liq_base:string;
tim_codi:string;
liq_sign:string;
aud_esta:string;
aud_usua:string;
aud_ufac:string;
liq_clas:string;
liq_secu:string;
}
export interface TOEcDphij {
  emp_codi:string;
cot_cont:string;
dph_cont:string;
dpp_cont:string;
pro_cont:string;
bod_codi:string;
dph_cant:string;
dph_valo:string;
dph_tdes:string;
dph_vdes:string;
dsp_codi:string;
dph_fech:string;
dph_tipo:string;
des_cont:string;
dph_desc:string;
ord_cont:string;
det_cont:string;
dph_vade:string;
pro_codi:string;
pro_nomb:string;
tip_codi:string;
uni_nomb:string;
bod_nomb:string;
dsp_nomb:string;
pro_padr:string;
}
export interface TOAeClase {
  emp_codi:string;
cla_cont:string;
cla_codi:string;
cla_nomb:string;
cla_clti:string;
aud_esta:string;
aud_ufac:string;
aud_usua:string;
lip_cont:string;
lip_conb:string;
lip_codi:string;
lip_coda:string;
lip_desc:string;
lip_desa:string;
cla_foto:string;
cla_nhab:string;
cla_mapp:string;
cla_pocl:string;
cla_tica:string;
cla_fchr:string;
cla_desc:string;
}
