export class RnAfili {
    public tip_codi: number;
    public tip_nomb: string;
    public afi_docu: string;
    public afi_feex: Date;
    public afi_nom1: string;
    public afi_nom2: string;
    public afi_ape1: string;
    public afi_ape2: string;
    public afi_fecn: Date;
    public afi_esci = '';
    public afi_cate: string;
    public afi_gene = '';
    public pro_cont: number;
    public pro_nomb: string;
    public ite_cont: number;
    public ite_nomb: string;
    public afi_cond = '';
    public pai_codi: number;
    public pai_nomb: string;
    public reg_codi: number;
    public reg_nomb: string;
    public dep_codi: number;
    public dep_nomb: string;
    public mun_codi: number;
    public mun_nomb: string;
    public loc_codi: number;
    public loc_nomb: string;
    public bar_codi: number;
    public bar_nomb: string;
    public afi_dire: string;
    public afi_mail: string;
    public afi_twit: string;
    public afi_wapp: string;
    public afi_face: string;
    public afi_tele: string;
    public afi_celu: string;

    // constructor()  {
    // this.afi_ape1 = 'morales';
    // this.afi_ape2 = 'leon';
    // this.afi_celu = '3107818709';
    // this.afi_cond = 'N';
    // this.afi_dire = 'CL 72 # 12 - 65';
    // this.afi_docu = '1024495170';
    // this.afi_esci = 'S';
    // this.afi_face = 'oscarml@hotmail.com';
    // this.afi_fecn = new Date();
    // this.afi_feex =  new Date();
    // this.afi_gene = 'M';
    // this.afi_mail = 'oscarml@gmail.com';
    // this.afi_nom1 = 'oscar';
    // this.afi_nom2 = 'ricardo';
    // this.afi_tele = '1234567';
    // this.afi_twit = '@ricardo';
    // this.afi_wapp = '+573107818709';
    // this.bar_codi = 1;
    // this.dep_codi = 11;
    // this.ite_cont = 10175;
    // this.ite_nomb = 'CONDICION ESPECIAL NULA';
    // this.loc_codi = 30;
    // this.mun_codi = 1;
    // this.pai_codi = 169;
    // this.pro_cont = 10652;
    // this.pro_nomb = 'ADMINISTRACION COMERCIAL Y DE MERCADEO';
    // this.reg_codi = 1;
    // this.tip_codi = 2;
    // this.tip_nomb = 'CEDULA DE CIUDADANIA';
    // }
}
