import { Cfcodeu } from './cfcodeu';
export class cfscrev {
  aud_esta: string;
  aud_usua: string;
  aud_ufac: Date;
  emp_codi: number;
  scr_cont: number;
  top_codi: number;
  scr_nume: number;
  scr_fech: Date;
  scr_esta: string;
  arb_sucu: number;
  cli_codi: number;
  scr_esci: string;
  scr_fevi: Date;
  scr_noca: string;
  scr_carg: string;
  scr_gcar: string;
  scr_tise: number;
  scr_vbas: number;
  scr_vpra: number;
  scr_vpta: number;
  scr_vptc: number;
  scr_vsua: number;
  scr_vaut: number;
  scr_vhoe: number;
  scr_vded: number;
  scr_vcme: number;
  scr_vprf: number;
  scr_vprc: number;
  scr_cali: string;
  scr_obse: string;
  scr_nhij: number;
  lic_cont: number;
  scr_vivi: string;
  scr_vsol: number;
  pai_codc: number;
  dep_codc: number;
  mun_codc: number;
  scr_diri: string;
  scr_teli: string;
  ite_cont: number;
  scr_vcom: number;
  scr_vsuv: number;
  scr_matr: string;
  tip_codi: number;
  pai_code: number;
  dep_code: number;
  mun_code: number;
  scr_vinm: number;
  scr_vegm: number;
  scr_nech: number;
  scr_anop: number;
  scr_mesp: number;
  scr_diap: number;
  ite_fami: number;
  ite_movi: number;
  tip_codf: number;
  ite_inca: number;
  dcl_codd: number;
  pai_codn: number;
  reg_codn: number;
  dep_codn: number;
  mun_codn: number;
  pai_codu: number;
  reg_codu: number;
  dep_codu: number;
  mun_codu: number;
  pai_codj: number;
  reg_codj: number;
  dep_codj: number;
  mun_codj: number;
  tip_codj: number;
  reg_codc: number;
  reg_code: number;
  pai_resi: number;
  dep_resi: number;
  mun_resi: number;
  scr_bres: string;
  scr_gene:string;
  scr_dire:string;
  scr_tele:number;
  scr_mail:string;
  scr_ncuo:number;
  scr_fpcu:Date;
  scr_nent:string;
  scr_teem:number;
  scr_diem:string;
  scr_exem:number;
  scr_sala:number;
  scr_care:string;
  codeudores: Cfcodeu[];
  constructor(){
    this.aud_esta= "";
    this.aud_usua= "";
    this.aud_ufac= new Date();
    this.emp_codi= 0;
    this.scr_cont= 0;
    this.top_codi= 0;
    this.scr_nume= 0;
    this.scr_fech= new Date();
    this.scr_esta= "";
    this.arb_sucu= 0;
    this.cli_codi= 0;
    this.scr_esci= "";
    this.scr_fevi= new Date();
    this.scr_noca= "";
    this.scr_carg= "";
    this.scr_gcar= "";
    this.scr_tise= 0;
    this.scr_vbas= 0;
    this.scr_vpra= 0;
    this.scr_vpta= 0;
    this.scr_vptc= 0;
    this.scr_vsua= 0;
    this.scr_vaut= 0;
    this.scr_vhoe= 0;
    this.scr_vded= 0;
    this.scr_vcme= 0;
    this.scr_vprf= 0;
    this.scr_vprc= 0;
    this.scr_cali= "";
    this.scr_obse= "";
    this.scr_nhij= 0;
    this.lic_cont= 0;
    this.scr_vivi= "";
    this.pai_codc= 0;
    this.dep_codc= 0;
    this.mun_codc= 0;
    this.scr_diri= "";
    this.scr_teli= "";
    this.ite_cont= 0;
    this.scr_vcom= 0;
    this.scr_vsuv= 0;
    this.scr_matr= "";
    this.tip_codi= 0;
    this.pai_code= 0;
    this.dep_code= 0;
    this.mun_code= 0;
    this.scr_vinm= 0;
    this.scr_vegm= 0;
    this.scr_nech= 0;
    this.scr_anop= 0;
    this.scr_mesp= 0;
    this.scr_diap= 0;
    this.ite_fami= 0;
    this.ite_movi= 0;
    this.tip_codf= 0;
    this.ite_inca= 0;
    this.dcl_codd= 0;
    this.pai_codn= 0;
    this.reg_codn= 0;
    this.dep_codn= 0;
    this.mun_codn= 0;
    this.pai_codu= 0;
    this.reg_codu= 0;
    this.dep_codu= 0;
    this.mun_codu= 0;
    this.pai_codj= 0;
    this.reg_codj= 0;
    this.dep_codj= 0;
    this.mun_codj= 0;
    this.tip_codj= 0;
    this.reg_codc= 0;
    this.reg_code= 0;
    this.pai_resi= 0;
    this.dep_resi= 0;
    this.mun_resi= 0;
    this.scr_bres= "";
    this.scr_gene="";
    this.scr_dire="";
    this.scr_tele=0;
    this.scr_mail="";
    this.scr_ncuo=0;
    this.scr_fpcu=new Date();
    this.scr_nent="";
    this.scr_teem=0;
    this.scr_diem="";
    this.scr_exem=0;
    this.scr_sala=0;
    this.scr_care="";
    this.codeudores=[];
  }
}
